### ISSUE TITLE
Error di langkah terakhir

### ISSUE THREAD

**Issue by iqbal2211** [syahrulyusuf97/keuangan#1]
Pas di langkah terakhir 
yg **php artisan make:useradmin**

kok muncul gini yah
solusinya gimana?

Failed creating user admin => PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'login' cannot be null in C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458
Stack trace:
#0 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(458): PDOStatement->execute()
#1 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `us...', Array)
#2 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(459): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(411): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2477): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 C:\xampp\htdocs\keuangan\app\Http\Controllers\CreateUser.php(16): Illuminate\Database\Query\Builder->insert(Array)
#7 C:\xampp\htdocs\keuangan\app\Console\Commands\makeUserAdmin.php(42): App\Http\Controllers\CreateUser::store()
#8 [internal function]: App\Console\Commands\makeUserAdmin->handle()
#9 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Command.php(184): Illuminate\Container\Container->call(Array)
#14 C:\xampp\htdocs\keuangan\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\makeUserAdmin), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\xampp\htdocs\keuangan\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'login' cannot be null (SQL: insert into `users` (`name`, `tempat_lahir`, `tgl_lahir`, `address`, `email`, `username`, `password`, `img`, `login`, `logout`) values (Your Name, Place of Birth, 2019-11-04, Your Address, your@email.com, admin, $2y$10$TUUTfazD1Df4xYyyxR0rwuJDwK4prF4aQLa4d7PVfjIDdeFisHX1S, , , )) in C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
Stack trace:
#0 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(459): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Connection.php(411): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2477): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 C:\xampp\htdocs\keuangan\app\Http\Controllers\CreateUser.php(16): Illuminate\Database\Query\Builder->insert(Array)
#5 C:\xampp\htdocs\keuangan\app\Console\Commands\makeUserAdmin.php(42): App\Http\Controllers\CreateUser::store()
#6 [internal function]: App\Console\Commands\makeUserAdmin->handle()
#7 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Command.php(184): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\keuangan\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Command.php(171): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\makeUserAdmin), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\keuangan\vendor\symfony\console\Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Console\Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\xampp\htdocs\keuangan\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\xampp\htdocs\keuangan\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}

**Comment by syahrulyusuf97** [comment]
Coba allow NULL field login & logout pada tabel users

**Comment by mustang86** [comment]
C:\laragon\www\keuangan (master)
λ php artisan migrate
Nothing to migrate.

C:\laragon\www\keuangan (master)
λ

**Comment by syahrulyusuf97** [comment]
> C:\laragon\www\keuangan (master)
> λ php artisan migrate
> Nothing to migrate.
> 
> C:\laragon\www\keuangan (master)
> λ
> 
> sepertinya ada masalah proses di bagian , php artisan migrate

Maaf ada kesalahan dalam proses update app, jadi untuk sementara belum bisa digunakan
